version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    environment:
      PORT: 4000
      DB: ${API_DB} # Ensure API_DB is defined in your .env file or environment variables
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    environment:
      PORT: 3000
      API_HOST: ${API_HOST} # Ensure API_HOST is defined in your .env file or environment variables
    depends_on:
      api:
        condition: service_started
    networks:
      - backend

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Use .env file or environment variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Use .env file or environment variables
      POSTGRES_DB: ${POSTGRES_DB} # Use .env file or environment variables
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Add ':ro' for read-only access to config file
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_healthy
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
