name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_API: yapadinithi/api
      DOCKER_IMAGE_WEB: yapadinithi/web

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build API Docker Image
      run: |
        docker build -t $DOCKER_IMAGE_API:latest ./api
        docker push $DOCKER_IMAGE_API:latest

    - name: Build Web Docker Image
      run: |
        docker build -t $DOCKER_IMAGE_WEB:latest ./web
        docker push $DOCKER_IMAGE_WEB:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 13.53.39.122
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Stop existing containers
          docker-compose down || true
          # Pull latest images
          docker pull $DOCKER_IMAGE_API:latest
          docker pull $DOCKER_IMAGE_WEB:latest
          # Restart application
          docker-compose up -d
